### ISSUE TITLE
Stops responding

### ISSUE THREAD

**Issue by Michael0Roslund** [NeoAcheron/midea-ac-py#13]
Home Assistant: 0.84.6 & midea==0.1.7

Works fine for a while and then the log is filled with these and the climate control also stops responding when using HA

2019-01-01 16:42:03 WARNING (MainThread) [homeassistant.components.climate] Updating midea climate took longer than the scheduled update interval 0:01:00

2019-01-01 16:41:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.midea_17592186052172 is taking over 10 seconds

Details:

`2019-01-01 16:40:11 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_17592186052172 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/config/custom_components/climate/midea.py", line 95, in async_update
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/deps/lib/python3.6/site-packages/midea/device.py", line 165, in apply
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 162, in appliance_transparent_send
    self.login()
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 118, in login
    'password': self.security.encryptPassword(self.login_id, self.password)
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 89, in api_request
    return self.api_request(endpoint, args)
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 89, in api_request
    return self.api_request(endpoint, args)
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 89, in api_request
    return self.api_request(endpoint, args)
  [Previous line repeated 946 more times]
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 83, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 224, in handle_api_error
    handler()
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 199, in restart_full
    self.get_login_id()
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 101, in get_login_id
    'loginAccount': self.login_account
  File "/config/deps/lib/python3.6/site-packages/midea/cloud.py", line 75, in api_request
    r = requests.post(url=url, data=data)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 315, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 280, in connection_from_url
    pool_kwargs=pool_kwargs)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 228, in connection_from_host
    return self.connection_from_context(request_context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 241, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 262, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 196, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 768, in __init__
    **conn_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 178, in __init__
    self.pool = self.QueueCls(maxsize)
  File "/usr/local/lib/python3.6/queue.py", line 39, in __init__
    self.not_empty = threading.Condition(self.mutex)
  File "/usr/local/lib/python3.6/threading.py", line 226, in __init__
    self._release_save = lock._release_save
RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by NeoAcheron** [comment]
Hi @Michael0yodi 

It seems like the retry is failing multiple on login after an API failure in the cloud. I'm unsure if this is a client side issue, it might be server side, but I will add better checking to report this better to Home Assistant.

**Comment by Michael0yodi** [comment]
Thanks for the reply, if it is on the server side would it make sense  (somehow) that it starts to work after a home assistant restart? also perhaps worth to mention if I start the Nethome plus app when seeing these errors it works without any issue, happy to test any suggestions
