### ISSUE TITLE
3123 the appliance is off line

### ISSUE THREAD

**Issue by seppe912** [NeoAcheron/midea-ac-py#18]
Hi,

i get following failure with python code:

Restarting session: '3004' - 'value is illegal.'
Retrying API call: 'homegroup/list/get'
Device list: [{'sn': '4b3c96a03a8fdabcec30621d25b5cd60323fc488eb69ccdff0e19b2cc666a4ced44b149fd94d953514a0c9e1a5765ddb', 'name': 'Master bedroom', 'modelNumber': '0', 'activeStatus': '1', 'id': 'XXXXXX', 'des': '', 'type': '0xAC', 'onlineStatus': '0'}]
Sending to XXXXXX: 5a5a01115700200000000000000000000e031214c679000000050a00000000000000000002000000aa1eac00000000000302408100ff03ff00300000000000000000000003bb8100000000000000000000000000000000
Traceback (most recent call last):
  File "midea.py", line 16, in <module>
    device.refresh()
  File "/usr/local/lib/python3.5/dist-packages/midea/device.py", line 143, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.5/dist-packages/midea/cloud.py", line 171, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.5/dist-packages/midea/cloud.py", line 83, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/usr/local/lib/python3.5/dist-packages/midea/cloud.py", line 224, in handle_api_error
    handler()
  File "/usr/local/lib/python3.5/dist-packages/midea/cloud.py", line 209, in throw
    raise ValueError(error_code, message)
ValueError: (3123, 'the appliance is off line.')

can you help me, whats wrong?
Greetings.

**Comment by seppe912** [comment]
ah okay, device is offline at the app too.
i think its a problem with my connection oder the Cloud...
sorry for Post
