### ISSUE TITLE
Error on startup HassIO 82.1

### ISSUE THREAD

**Issue by jchasey** [NeoAcheron/midea-ac-py#2]
2018-12-03 05:53:47 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform midea
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/climate/midea.py", line 50, in async_setup_platform
    entities = [MideaClimateDevice(device, temp_step) for device in devices]
  File "/config/custom_components/climate/midea.py", line 50, in <listcomp>
    entities = [MideaClimateDevice(device, temp_step) for device in devices]
  File "/config/custom_components/climate/midea.py", line 66, in __init__
    device.refresh()
  File "/config/deps/lib/python3.6/site-packages/midea/device.py", line 82, in refresh
    self.update(response)
  File "/config/deps/lib/python3.6/site-packages/midea/device.py", line 106, in update
    self._operational_mode = operational_mode_enum(res.operational_mode)
  File "/usr/local/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/usr/local/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 0 is not a valid operational_mode_enum

**Comment by jchasey** [comment]
Just to add this is with a Invmate EVA II Dehumidifier which shows up correctly in the Midea iPhone app.

**Comment by NeoAcheron** [comment]
Unfortunately dehumidifiers doesn't seem to be supported right now, however, I think it might be easy enough to add now that the protocol is working. 

Temporarily though, what you could do is add another value to the `operational_mode_enum` in `device.py` with a value of 0.

That should allow you to move to the next step to see what else is compatible. 

I'm thinking of a way to make this easier though. Perhaps some debug would be useful, as it seems that every AC reports data slightly differently as well.

**Comment by jchasey** [comment]
Ah, didn't realise there was not yet the dehumidifier support. However as you say should be in theory straightforward. Happy to be a guinea pig and help debug. Will try the operational mode tweak suggested and report back.

**Comment by kiowaro** [comment]
I also have an EVA II Dehumidifier  and I have added value 0 to operational_mode_enum.
Then it complained about a missing value 45 in swing_mode_enum.
After I added the missing values, the component showed up in Home Assistant interface but I can not control my dehumidifier from HA.

**Comment by NeoAcheron** [comment]
I think the way the devices are handled needs to be re-evaluated. There is a `type` field that comes back from the cloud API when the appliances are listed. I'll make a change in the way the devices are instantiated in order to properly distinguish the different device types.

I don't think it would be a good idea to add all of the Dehumidifier values to the AC device's enums. Currently the plugin doesn't distinguish between AC's and dehumidifiers and I don't want to end up with a device that has too many options that are not supported. 

I will amend the device class and abstract the types accordingly. I'll make provision for different device types, then the blanks can be filled in once we have proper debug output.

**Comment by NeoAcheron** [comment]
I've made a change to handle dehumidifiers differently to the AC appliances. There is a whole bunch of new debug if running with `__debug__` set to `true`. To make things easier to test, can you please look at the Basic Sample code in the Wiki and send me the output of the debug in a private message.

I don't have a dehumidifier, so its hard for me to test, but with the debug, I can definitely try implementing basic support. Additionally, can you please answer the following questions:
* What modes does the appliance support? (On, Off, Cool, Dry, Heat, Fan, etc)
* Does it have fan speed control? (If yes, what speeds)
* Does it have a temperature setting? (and what range)
* Does the app report the room temperature?
* Is there a swing function?
* Does it beep when changes are applied via the app?
* Are there any status fields that should be looked at?

It would also be useful to try different settings and printing the debug output from each.

**Comment by kiowaro** [comment]
What modes does the appliance support? (On, Off, Cool, Dry, Heat, Fan, etc)
- On
- Off
- Smart
- Continuous
- Dryer
- Dehumidifier

Does it have fan speed control? (If yes, what speeds)
- Silent
- Medium
- Turbo

Does it have a temperature setting? (and what range)
- No, but it has a target humidity setting

Does the app report the room temperature?
- No, but it reports the humidity

Is there a swing function?
-No

 Does it beep when changes are applied via the app?
- Yes

Are there any status fields that should be looked at?
- Room Humidity

Other:
- The user should be able to set a Target Humidity
- There is also a ion releasing function
- The Midea app also has a timer (schedule function by day / hour to turn On/Off the appliance) - I will have to check to see if this works as it is not implemented in the Invmate app but the main functions would be to turn it On and Off, to change modes and to read and set humidity levels.

I will PM you once I have the debug output.
