### ISSUE TITLE
New Version 0.1.0 error under Hassio 0.83.2

### ISSUE THREAD

**Issue by kegra** [NeoAcheron/midea-ac-py#7]
Thu Dec 06 2018 14:18:36 GMT+0200 (EET)

Error while setting up platform midea
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/climate/midea.py", line 50, in async_setup_platform
    devices = clnt.devices()
  File "/config/deps/lib/python3.6/site-packages/midea/client.py", line 51, in devices
    current_device.set_status(device_status)
AttributeError: 'air_conditioning_device' object has no attribute 'set_status'

**Comment by NeoAcheron** [comment]
Apologies, I think this was missed when I refactored for supporting dehumidifiers.

**Comment by NeoAcheron** [comment]
I have resolved the issue, please update your component to 0.1.1 and try again.
