### ISSUE TITLE
from midea.device import operational_mode_enum

### ISSUE THREAD

**Issue by ruben0909** [NeoAcheron/midea-ac-py#8]
At first. thank you for your awesome work
**Info**
Hass version: 0.83.3
Environment: pyenv 
Python: 3.6

**Trace**
```
2018-12-06 15:16:31 INFO (MainThread) [homeassistant.components.climate] Setting up climate.midea
Device list: [{'des': '', 'activeStatus': '1', 'onlineStatus': '1', 'name': 'Sala32F7', 'modelNumber': '0', 'id': '10995116285415', 'sn': '0a199725af1789c5fa2a566bd606e781fced8a85dedb0ef0a35cc21787386a934c942ffdc91fa585a3fe3f1dc9f2d118', 'type': '0xAC'}, {'des': '', 'activeStatus': '1', 'onlineStatus': '1', 'name': 'Dormitorio6AB0', 'modelNumber': '0', 'id': '12094627913115', 'sn': '0a199725af1789c5fa2a566bd606e781b1a70bfe1e38582bd83eb7ac691f87f64c942ffdc91fa585a3fe3f1dc9f2d118', 'type': '0xAC'}, {'des': '', 'activeStatus': '1', 'onlineStatus': '1', 'name': 'Air ConditionerD69D', 'modelNumber': '0', 'id': '12094627914315', 'sn': '0a199725af1789c5fa2a566bd606e781ee5f6a15994a2196d3f40edae66ac8d14c942ffdc91fa585a3fe3f1dc9f2d118', 'type': '0xAC'}]
2018-12-06 15:13:46 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform midea
Traceback (most recent call last):
  File "/share/CACHEDEV2_DATA/Public/NASApps/hass/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/share/CACHEDEV2_DATA/.qpkg/QPython3/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/share/CACHEDEV2_DATA/.qpkg/QPython3/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/share/CACHEDEV2_DATA/.qpkg/QPython3/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/share/CACHEDEV2_DATA/Public/NASApps/hass/.homeassistant/custom_components/climate/midea.py", line 54, in async_setup_platform
    entities.append(MideaClimateACDevice(device, temp_step))
  File "/share/CACHEDEV2_DATA/Public/NASApps/hass/.homeassistant/custom_components/climate/midea.py", line 67, in __init__
    from midea.device import operational_mode_enum
```

Id and s/n modified
**Related**
#2  But I have 3 Air Conditioners 0xAC not Humidifier

**Comment by NeoAcheron** [comment]
Apologies. More oversight on my part, I will attempt to resolve these issues later

**Comment by NeoAcheron** [comment]
I've resolved this issue, please update your component and try again.

**Comment by ruben0909** [comment]
It works perfectly 👍 
Thank you, thank you, thank you. 😄
